"""empty message

Revision ID: f1fbf294115d
Revises: 63b9b9638086
Create Date: 2019-02-24 19:57:29.854615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fbf294115d'
down_revision = '63b9b9638086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funcionarios')
    # ### end Alembic commands ###
